### PR TITLE
Update electron-webpack for use Webpack 4 and Babel 7

### PR DESCRIPTION
**Pull request by loeck**

### CODE REVIEW

**Comment by gre** [comment]
This PR created a nasty regression on some very nasty bug with React. in PROD mode only, things was getting randomly unmounted.

**This cost us weeks to find this bug. Let's never migrate to anything "beta" concerning critical things like build tools.**

We have to revert this PR.

**Comment by meriadec** [comment]
Wow..

**Comment by gre** [comment]
at least i think. but well, i tried JUST before this commit vs JUST after this commit.
this is the diff to apply to try it:

```diff
diff --git a/package.json b/package.json
index 58234eb4..a1be703e 100644
--- a/package.json
+++ b/package.json
@@ -48,6 +48,7 @@
     "@ledgerhq/hw-app-eth": "^4.7.3",
     "@ledgerhq/hw-transport": "^4.7.3",
     "@ledgerhq/hw-transport-node-hid": "^4.7.3",
+    "animated": "^0.2.2",
     "axios": "^0.18.0",
     "babel-runtime": "^6.26.0",
     "bcryptjs": "^2.4.3",
diff --git a/src/index.ejs b/src/index.ejs
index db8f5c25..b9801be0 100644
--- a/src/index.ejs
+++ b/src/index.ejs
@@ -45,40 +45,24 @@
     </div>
     <div id="app"></div>
     <script>
-      const { name } = require('electron').remote.getCurrentWindow()
+    const { name } = require('electron').remote.getCurrentWindow()

-      const preloadEl = document.getElementById('preload')
-      const appEl = document.getElementById('app')
+const preloadEl = document.getElementById('preload')
+const appEl = document.getElementById('app')

-      const initApp = (options = {}) => {
-        const { force = false } = options
+const initApp = (options = {}) => {
+  const { force = false } = options

-        if (force) {
-          preloadEl.remove()
-        } else {
-          preloadEl.style.opacity = 0
+  if (force) {
+    preloadEl.remove()
+  } else {
+    preloadEl.style.opacity = 0

-          preloadEl.addEventListener('transitionend', () => preloadEl.remove())
-        }
-      }
-
-      if (name === 'MainWindow') {
-        preloadEl.style.display = 'flex'
-
-        let waitTime = 0
-
-        const PRELOAD_WAIT_TIME_MIN = 2e3
-        const interval = setInterval(() => (waitTime += 250), 250)
+    preloadEl.addEventListener('transitionend', () => preloadEl.remove())
+  }
+}

-        window.onAppReady = () => {
-          const delay = PRELOAD_WAIT_TIME_MIN - waitTime
-
-          clearInterval(interval)
-          setTimeout(initApp, delay > 0 ? delay : 1)
-        }
-      } else {
-        initApp({ force: true })
-      }
-    </script>
+initApp({ force: true })
+</script>
   </body>
 </html>
diff --git a/src/renderer/init.js b/src/renderer/init.js
index 9be31456..7fb22f61 100644
--- a/src/renderer/init.js
+++ b/src/renderer/init.js
@@ -1,61 +1,7 @@
-// @flow
-
 import React from 'react'
-import { remote } from 'electron'
 import { render } from 'react-dom'
-import { AppContainer } from 'react-hot-loader'
-import createHistory from 'history/createHashHistory'
-
-import createStore from 'renderer/createStore'
-import events from 'renderer/events'
-
-import { fetchAccounts } from 'actions/accounts'
-import { fetchSettings } from 'actions/settings'
-import { initCounterValues } from 'actions/counterValues'
-import { isLocked } from 'reducers/application'
-import { getLanguage } from 'reducers/settings'
-
-import db from 'helpers/db'
-
-import App from 'components/App'
-
-import 'styles/global'
-
-// Init db with defaults if needed
-db.init('settings', {})
-db.init('counterValues', {})
+import ConfettiParty from './ConfettiParty'

-const history = createHistory()
-const store = createStore(history)
 const rootNode = document.getElementById('app')

-store.dispatch(fetchSettings())
-store.dispatch(initCounterValues())
-
-const state = store.getState() || {}
-const language = getLanguage(state)
-const locked = isLocked(state)
-
-function r(Comp) {
-  if (rootNode) {
-    render(<AppContainer>{Comp}</AppContainer>, rootNode)
-  }
-}
-
-async function init() {
-  if (!locked) {
-    // Init accounts with defaults if needed
-    db.init('accounts', [])
-
-    await store.dispatch(fetchAccounts())
-  }
-
-  r(<App store={store} history={history} language={language} />)
-
-  // Only init events on MainWindow
-  if (remote.getCurrentWindow().name === 'MainWindow') {
-    events({ store, locked })
-  }
-}
-
-init()
+if (rootNode) render(<ConfettiParty emit={false} />, rootNode)
diff --git a/yarn.lock b/yarn.lock
index 602a3d9e..cb2e48fb 100644
--- a/yarn.lock
+++ b/yarn.lock
@@ -472,6 +472,13 @@ amdefine@>=0.0.4:
   version "1.0.1"
   resolved "https://registry.yarnpkg.com/amdefine/-/amdefine-1.0.1.tgz#4a5282ac164729e93619bcfd3ad151f817ce91f5"

+animated@^0.2.2:
+  version "0.2.2"
+  resolved "https://registry.yarnpkg.com/animated/-/animated-0.2.2.tgz#04af7846ad0b9b8d1f0472cc53d82b8efeb4a751"
+  dependencies:
+    invariant "^2.2.0"
+    normalize-css-color "^1.0.1"
+
 ansi-align@^2.0.0:
   version "2.0.0"
   resolved "https://registry.yarnpkg.com/ansi-align/-/ansi-align-2.0.0.tgz#c36aeccba563b89ceb556f3690f0b1d9e3547f7f"
@@ -6633,6 +6640,9 @@ ledger-test-library@KhalilBellakrid/ledger-test-library-nodejs#7d37482:
   dependencies:
     axios "^0.17.1"
     bindings "^1.3.0"
+    electron "^1.8.2"
+    electron-builder "^20.0.4"
+    electron-rebuild "^1.7.3"
     nan "^2.6.2"
     prebuild-install "^2.2.2"

@@ -7385,6 +7395,10 @@ nopt@^4.0.1:
     abbrev "1"
     osenv "^0.1.4"

+normalize-css-color@^1.0.1:
+  version "1.0.2"
+  resolved "https://registry.yarnpkg.com/normalize-css-color/-/normalize-css-color-1.0.2.tgz#02991e97cccec6623fe573afbbf0de6a1f3e9f8d"
+
 normalize-package-data@^2.3.2, normalize-package-data@^2.3.4, normalize-package-data@^2.4.0:
   version "2.4.0"
   resolved "https://registry.yarnpkg.com/normalize-package-data/-/normalize-package-data-2.4.0.tgz#12f95a307d58352075a04907b84ac8be98ac012f"
```

**Comment by gre** [comment]
oh and with the ConfettiLayer folder in renderer (with using a custom image for the confetti img )

**Comment by gre** [comment]
ouch. the PR is not easy to revert because there are things unrelated to babel changes..

**Comment by meriadec** [comment]
Also, having a `.js` Babel config is a pain if we just want to use babel-node in simple scripts. Would be very cool to get back to plain `.babelrc`

**Comment by gre** [comment]
well. that's why we need more atomic commits XD

**Comment by gre** [comment]
@meriadec agreed. especially we don't want to minimify the CSS class. it's a bad idea for Sentry. otherwsie the error are very cryptic

**Comment by gre** [comment]
I give up. i can't easily rollback. so many things have changed –_–

**Pull request merged**
